name: push-transition-to-master
on:
   push:
     branches:
       - master
       - feature/lightspeed-transition
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: sync with master
        id: pull
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "feature/lightspeed-transition"
          PULL_REQUEST_TITLE: "Sync up lightspeed-transition with master"
          CONTENT_COMPARISON: true
      - name: second step
        uses: tretuna/sync-branches@1.4.0
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "feature/lightspeed-transition"
          TO_BRANCH: "master"
          PULL_REQUEST_TITLE: "[CAT-10308] merge lightspeed -> master"
          CONTENT_COMPARISON: true
