name: push-transition-to-master
on:
  push:
    branches: [ "master", "feature/lightspeed-transition" ]
  pull_request:
    branches: [ "master", "feature/lightspeed-transition" ]

jobs:
  updateBranch:
    name: Update master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/master'
      with:
        branch: "feature/lightspeed-transition"
        force: 1
 
