name: push-transition-to-master
on:
  push:
    branches: [ "master", "feature/lightspeed-transition" ]
  pull_request:
    branches: [ "master", "feature/lightspeed-transition" ]

jobs:
  updateBranch:
    name: Update master
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: Embraser01/update-git-branch-action@v1.0.0
      if: github.ref == 'refs/heads/master'
      with:
        branch: "feature/lightspeed-transition"
        force: 1
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-18.04
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          DRY_RUN: "false"
          PR_FILTER: "labelled"
          PR_LABELS: "autoupdate,keep up-to-date,integration"
          EXCLUDED_LABELS: "dependencies,wontfix"
          MERGE_MSG: "Branch was auto-updated."
          RETRY_COUNT: "5"
          RETRY_SLEEP: "300"
          MERGE_CONFLICT_ACTION: "fail"
