name: push-transition-to-master
on:
  push:
    branches: [ "master", "feature/lightspeed-transition" ]
  pull_request:
    branches: [ "master", "feature/lightspeed-transition" ]

jobs:
  update-branches:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Update branches
        uses: brainly/action-autoupdate-branch@2.0.0
        id: autoUpdateBranch
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          requiredApprovals: 1 #Number of required approvals before branch should be updated
