name: manual-transition
on:
   push:
     branches:
       - master
       - feature/lightspeed-transition
env:
   _GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
   _FROM_BRANCH: "master"
   _TO_BRANCH: "feature/lightspeed-transition"
   _PULL_REQUEST_TITLE: "Sync up lightspeed-transition with master"
   _CONTENT_COMPARISON: true

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
          - name: Checkout
            uses: actions/checkout@v3
          - name: update-brances
            run: |
               echo ${{ github.ref }}
               git fetch origin
               
           
