name: manual-transition
on:
   push:
     branches:
       - master
       - feature/lightspeed-transition
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "master"
          TO_BRANCH: "feature/lightspeed-transition"
          PULL_REQUEST_TITLE: "Sync up lightspeed-transition with master"
          CONTENT_COMPARISON: true
          REVIEWERS:
           -waldomilanes
        run: |
          echo GITHUB_ACTION
